-- CREATE TABLES WITH CONSTRAINTS

CREATE TABLE Users (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Phone VARCHAR(20) UNIQUE NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Vendors (
    VendorID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Category VARCHAR(100) NOT NULL,
    RegistrationDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    Status ENUM('Active', 'Inactive') NOT NULL DEFAULT 'Active'
);

CREATE TABLE Accounts (
    AccountID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT,
    VendorID INT,
    Balance DECIMAL(15,2) NOT NULL CHECK (Balance >= 0),
    AccountType ENUM('User', 'Vendor') NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (VendorID) REFERENCES Vendors(VendorID) ON DELETE SET NULL
);

CREATE TABLE FinancialTransactions (
    TransactionID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    VendorID INT NOT NULL,
    Amount DECIMAL(15,2) NOT NULL CHECK (Amount > 0),
    TransactionType ENUM('Deposit', 'Withdrawal', 'Purchase') NOT NULL,
    Status ENUM('Pending', 'Completed', 'Failed') NOT NULL DEFAULT 'Pending',
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (VendorID) REFERENCES Vendors(VendorID) ON DELETE CASCADE
);

CREATE TABLE MarketData (
    MarketID INT PRIMARY KEY AUTO_INCREMENT,
    VendorID INT NOT NULL,
    Price DECIMAL(15,2) NOT NULL CHECK (Price > 0),
    Currency VARCHAR(3) NOT NULL,
    Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VendorID) REFERENCES Vendors(VendorID) ON DELETE CASCADE
);

CREATE TABLE Audits (
    AuditID INT PRIMARY KEY AUTO_INCREMENT,
    EntityID INT NOT NULL,
    EntityType VARCHAR(100) NOT NULL,
    ChangeType ENUM('Insert', 'Update', 'Delete') NOT NULL,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    PerformedBy INT NOT NULL,
    FOREIGN KEY (PerformedBy) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE Disputes (
    DisputeID INT PRIMARY KEY AUTO_INCREMENT,
    TransactionID INT NOT NULL,
    UserID INT NOT NULL,
    Status ENUM('Open', 'Resolved', 'Closed') NOT NULL DEFAULT 'Open',
    Resolution TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TransactionID) REFERENCES FinancialTransactions(TransactionID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);



